-- Populate New Schema Tables
-- Migration to enhance database with missing data in new schema tables

-- First, ensure all connector types are populated
-- This will run the seed script logic directly in the migration
INSERT INTO "ConnectorType" (code, "nominalPins", description, "voltageClass", remarks)
VALUES
  -- 74-Pin Intercar Connector (Primary connector type)
  ('74P', 74, '74-Pin Intercar Connector', '110V', 'Standard 74-pin connector for intercar connections between train cars'),
  
  -- Standard Connector Series
  ('CN', NULL, 'Standard Connector', NULL, 'Generic connector type used across multiple systems'),
  ('CN1', NULL, 'CN1 Series Connector', NULL, 'CN1 series connector - first connector in a group'),
  ('CN2', NULL, 'CN2 Series Connector', NULL, 'CN2 series connector - second connector in a group'),
  ('CN3', NULL, 'CN3 Series Connector', NULL, 'CN3 series connector - third connector in a group'),
  ('CN4', NULL, 'CN4 Series Connector', NULL, 'CN4 series connector - fourth connector in a group'),
  ('CN5', NULL, 'CN5 Series Connector', NULL, 'CN5 series connector - fifth connector in a group'),
  
  -- X-Series Connectors (CAB connectors)
  ('X', NULL, 'X-Series Connector', NULL, 'X-series connector base type'),
  ('X1', 74, 'X1 Connector', '110V', 'X1 connector for CAB (Cab) systems - 74P jumper plug'),
  ('X2', 74, 'X2 Connector', '110V', 'X2 connector for CAB (Cab) systems - 74PW jumper plug'),
  ('X3', 11, 'X3 Connector', '415VAC', 'X3 connector for 415V AC / 230V AC'),
  ('X4', NULL, 'X4 Connector', '110V', 'X4 connector for CAB (Cab) systems'),
  
  -- J-Series Connectors (EDB Panel connectors)
  ('J', NULL, 'J-Series Connector', NULL, 'J-series connector for EDB panels'),
  ('J1', NULL, 'J1 Connector', '110V', 'J1 connector for EDB (Emergency Door Bypass) panels'),
  ('J2', NULL, 'J2 Connector', '110V', 'J2 connector for EDB panels'),
  ('J3', NULL, 'J3 Connector', '110V', 'J3 connector for EDB panels'),
  ('J4', NULL, 'J4 Connector', '110V', 'J4 connector for EDB panels'),
  
  -- P-Series Connectors (Panel connectors)
  ('P', NULL, 'Panel Connector', NULL, 'Panel-mounted connector base type'),
  ('P1', NULL, 'P1 Panel Connector', NULL, 'P1 panel-mounted connector'),
  ('P2', NULL, 'P2 Panel Connector', NULL, 'P2 panel-mounted connector'),
  ('P3', NULL, 'P3 Panel Connector', NULL, 'P3 panel-mounted connector'),
  
  -- Additional common connector types
  ('TB', NULL, 'Terminal Block', NULL, 'Terminal block connector'),
  ('PL', NULL, 'Plug Connector', NULL, 'Plug-type connector'),
  ('SK', NULL, 'Socket Connector', NULL, 'Socket-type connector'),
  ('JP', NULL, 'Jumper Connector', NULL, 'Jumper connector for configuration'),
  ('SW', NULL, 'Switch Connector', NULL, 'Switch-type connector'),
  ('M12', NULL, 'M12 Ethernet connector port', NULL, 'Industrial Ethernet M12 connector'),
  ('X01', NULL, 'Interface connector for VAC systems', NULL, 'VAC system interface connector'),
  ('X02', NULL, 'Interface connector for I/O modules', NULL, 'I/O module interface connector'),
  ('X03', NULL, 'Interface connector for control circuits', NULL, 'Control circuit interface connector'),
  ('X10', NULL, 'Connector for CBTC', NULL, 'Communication Based Train Control connector')

ON CONFLICT (code) DO NOTHING;

-- Create Drawing Verification Status for all drawings
INSERT INTO "DrawingVerificationStatus" (
  id, "drawingId", "drawingNumber", status, "verificationDate", "verifiedBy", 
  notes, "pagesVerified", "totalPages", confidence, extra, "createdAt", "updatedAt"
)
SELECT 
  gen_random_uuid() as id,
  d.id as "drawingId",
  d."drawingNo" as "drawingNumber",
  CASE 
    WHEN d."isSynced" THEN 'VERIFIED' 
    ELSE 'UNVERIFIED' 
  END as status,
  CASE 
    WHEN d."syncedAt" IS NOT NULL THEN d."syncedAt"
    WHEN d."isSynced" THEN NOW()
    ELSE NULL
  END as "verificationDate",
  'System' as "verifiedBy",
  CASE 
    WHEN d."isSynced" THEN 'Auto-verified during schema upgrade'
    ELSE 'Pending verification'
  END as notes,
  COALESCE(d."totalSheets", 1) as "pagesVerified",
  COALESCE(d."totalSheets", 1) as "totalPages",
  CASE 
    WHEN d."isSynced" THEN 0.95 
    WHEN d."totalSheets" > 0 THEN 0.85
    ELSE 0.75 
  END as confidence,
  jsonb_build_object(
    'autoGenerated', true, 
    'source', 'schema_migration_20260717',
    'connectorCount', (SELECT COUNT(*) FROM "Connector" c WHERE c."drawingId" = d.id),
    'wireCount', (SELECT COUNT(*) FROM "Wire" w WHERE EXISTS (
      SELECT 1 FROM "DrawingWire" dw WHERE dw."drawingId" = d.id AND dw."wireId" = w.id
    ))
  ) as extra,
  NOW() as "createdAt",
  NOW() as "updatedAt"
FROM "Drawing" d
WHERE NOT EXISTS (
  SELECT 1 FROM "DrawingVerificationStatus" dvs 
  WHERE dvs."drawingId" = d.id
);

-- Create basic Equipment records from Device data
-- This creates a simplified equipment catalog
INSERT INTO "Equipment" (
  id, name, code, "subsystemId", manufacturer, model, "partNumber", 
  description, metadata, "createdAt", "updatedAt"
)
SELECT 
  gen_random_uuid() as id,
  DISTINCT 
  d."deviceName" as name,
  UPPER(REPLACE(REPLACE(d."deviceName", ' ', '_'), '/', '_')) as code,
  d."subsystemId" as "subsystemId",
  COALESCE(d."manufacturerRef", 'Unknown') as manufacturer,
  NULL as model,
  d."tagNo" as "partNumber",
  CONCAT('Auto-generated from device: ', d."deviceName") as description,
  jsonb_build_object(
    'autoGenerated', true,
    'source', 'device_data_migration',
    'originalTagNo', d."tagNo",
    'deviceCount', COUNT(*) OVER (PARTITION BY d."deviceName")
  ) as metadata,
  NOW() as "createdAt",
  NOW() as "updatedAt"
FROM "Device" d
WHERE d."deviceName" IS NOT NULL
  AND LENGTH(d."deviceName") > 0
  AND NOT EXISTS (
    SELECT 1 FROM "Equipment" e 
    WHERE e.code = UPPER(REPLACE(REPLACE(d."deviceName", ' ', '_'), '/', '_'))
  )
ORDER BY d."deviceName";

-- Create basic Device Specifications
INSERT INTO "DeviceSpecification" (
  id, "deviceId", "specCode", "specName", "specValue", unit, category, 
  verified, source, extra, "createdAt", "updatedAt"
)
SELECT 
  gen_random_uuid() as id,
  d.id as "deviceId",
  'DESCRIPTION' as "specCode",
  'Description' as "specName",
  d."deviceName" as "specValue",
  NULL as unit,
  'General' as category,
  true as verified,
  'Migration' as source,
  jsonb_build_object(
    'autoGenerated', true,
    'migrationDate', NOW()
  ) as extra,
  NOW() as "createdAt",
  NOW() as "updatedAt"
FROM "Device" d
WHERE d."deviceName" IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM "DeviceSpecification" ds 
    WHERE ds."deviceId" = d.id AND ds."specCode" = 'DESCRIPTION'
  );

-- Add more detailed specifications where available
INSERT INTO "DeviceSpecification" (
  id, "deviceId", "specCode", "specName", "specValue", unit, category, 
  verified, source, extra, "createdAt", "updatedAt"
)
SELECT 
  gen_random_uuid() as id,
  d.id as "deviceId",
  'TAG_NUMBER' as "specCode",
  'Tag Number' as "specName",
  d."tagNo" as "specValue",
  NULL as unit,
  'Identification' as category,
  true as verified,
  'Migration' as source,
  jsonb_build_object(
    'autoGenerated', true,
    'migrationDate', NOW()
  ) as extra,
  NOW() as "createdAt",
  NOW() as "updatedAt"
FROM "Device" d
WHERE d."tagNo" IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM "DeviceSpecification" ds 
    WHERE ds."deviceId" = d.id AND ds."specCode" = 'TAG_NUMBER'
  );

-- Create Cable records from wire data
INSERT INTO "Cable" (
  id, "cableNumber", "cableType", "coreCount", manufacturer, "partNumber",
  routing, length, description, metadata, status, "createdAt", "updatedAt"
)
SELECT 
  gen_random_uuid() as id,
  DISTINCT w."cableSpec" as "cableNumber",
  CASE 
    WHEN w."wireSize" LIKE '%x%' THEN 'MULTI_CORE'
    ELSE 'SINGLE_CORE'
  END as "cableType",
  NULL as "coreCount",
  'Unknown' as manufacturer,
  NULL as "partNumber",
  NULL as routing,
  NULL as length,
  CONCAT('Auto-generated from wire specification: ', w."cableSpec") as description,
  jsonb_build_object(
    'autoGenerated', true,
    'source', 'wire_data_migration',
    'wireCount', COUNT(*) OVER (PARTITION BY w."cableSpec"),
    'voltageClasses', ARRAY_AGG(DISTINCT w."voltageClass") FILTER (WHERE w."voltageClass" IS NOT NULL)
  ) as metadata,
  'active' as status,
  NOW() as "createdAt",
  NOW() as "updatedAt"
FROM "Wire" w
WHERE w."cableSpec" IS NOT NULL
  AND LENGTH(w."cableSpec") > 0
  AND NOT EXISTS (
    SELECT 1 FROM "Cable" c 
    WHERE c."cableNumber" = w."cableSpec"
  )
ORDER BY w."cableSpec";

-- Update existing connectors to reference proper connector types where possible
UPDATE "Connector" 
SET "connectorTypeCode" = 'X1'
WHERE "connectorCode" LIKE 'X1%'
  AND "connectorTypeCode" IS NULL;

UPDATE "Connector" 
SET "connectorTypeCode" = 'X2'
WHERE "connectorCode" LIKE 'X2%'
  AND "connectorTypeCode" IS NULL;

UPDATE "Connector" 
SET "connectorTypeCode" = 'X3'
WHERE "connectorCode" LIKE 'X3%'
  AND "connectorTypeCode" IS NULL;

UPDATE "Connector" 
SET "connectorTypeCode" = 'X4'
WHERE "connectorCode" LIKE 'X4%'
  AND "connectorTypeCode" IS NULL;

UPDATE "Connector" 
SET "connectorTypeCode" = 'J1'
WHERE "connectorCode" LIKE 'J1%'
  AND "connectorTypeCode" IS NULL;

UPDATE "Connector" 
SET "connectorTypeCode" = 'J2'
WHERE "connectorCode" LIKE 'J2%'
  AND "connectorTypeCode" IS NULL;

UPDATE "Connector" 
SET "connectorTypeCode" = 'CN1'
WHERE "connectorCode" LIKE 'CN1%'
  AND "connectorTypeCode" IS NULL;

-- Verification queries
SELECT 'Migration completed successfully' as status;

-- Summary statistics
SELECT 
  (SELECT COUNT(*) FROM "ConnectorType") as "total_connector_types",
  (SELECT COUNT(*) FROM "DrawingVerificationStatus") as "verified_drawings",
  (SELECT COUNT(*) FROM "Equipment") as "equipment_count",
  (SELECT COUNT(*) FROM "DeviceSpecification") as "specifications_count",
  (SELECT COUNT(*) FROM "Cable") as "cable_count";