#!/bin/bash

# VERCEL ENVIRONMENT VARIABLES SETUP
# This script sets the required environment variables in Vercel

echo "🔧 Vercel Environment Variables Setup"
echo "======================================"
echo ""
echo "You need to set these environment variables in Vercel manually:"
echo ""
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Click: vcc-system-application project"
echo "3. Go to: Settings → Environment Variables"
echo "4. Add these variables:"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "Variable: DATABASE_URL"
echo "Value:    postgresql://neondb_owner:npg_KyjXIOVCDW32@ep-tiny-mode-aq7698gi-pooler.c-8.us-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
echo "Environments: Production, Preview, Development"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "Variable: DIRECT_URL"
echo "Value:    postgresql://neondb_owner:npg_KyjXIOVCDW32@ep-tiny-mode-aq7698gi-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require"
echo "Environments: Production, Preview, Development"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "5. Click 'Save'"
echo "6. Trigger redeploy:"
echo "   - Go to: Deployments tab"
echo "   - Click 'Redeploy' on latest deployment"
echo "   - OR push new commit: git commit --allow-empty -m 'chore: trigger redeploy with env vars'"
echo ""
echo "Alternative: Use Vercel CLI"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "If you have Vercel CLI installed, run:"
echo ""
echo "vercel env add DATABASE_URL"
echo "# Paste: postgresql://neondb_owner:npg_KyjXIOVCDW32@ep-tiny-mode-aq7698gi-pooler.c-8.us-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
echo ""
echo "vercel env add DIRECT_URL"
echo "# Paste: postgresql://neondb_owner:npg_KyjXIOVCDW32@ep-tiny-mode-aq7698gi-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require"
echo ""
echo "vercel redeploy"
echo ""
echo "────────────────────────────────────────────────────────────"
